#!/usr/bin/env python3
"""build_hrtf.py -- generate the firmware's DSP coefficient tables.

Vendor: Illicit Apothecary
Project: Quad Preamp and Recorder

Run this whenever you change anything in qpr_ambisonics.py, or when you want to
retune the microphone geometry. It writes:

    lib/qpr_dsp/qpr_coeffs.h    compiled into the firmware (the default set)
    HRTF.BIN                    optional, copy to the SD card to override it

The firmware never recomputes any of this. That is deliberate: the filters you
hear in simulate_binaural.py on your desktop are the exact same numbers the
Teensy convolves, so tuning on the desktop is meaningful.

Usage
-----
    python3 build_hrtf.py                       # analytic model -> C header
    python3 build_hrtf.py --taps 128            # cheaper filters
    python3 build_hrtf.py --radius 0.021        # your measured capsule radius
    python3 build_hrtf.py --sofa KEMAR.sofa --bin HRTF.BIN
                                                # measured set -> SD card file

The --sofa path needs the `sofar` package (pip install sofar). Without it the
analytic model is used and the script says so.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

import qpr_ambisonics as qa

MAGIC = b"QPRH"
FORMAT_VERSION = 1


def make_sofa_provider(path: str, verbose: bool = True):
    """Return an hrir_provider backed by a measured SOFA set, or None."""
    try:
        import sofar  # type: ignore
    except ImportError:
        print(
            f"  ! 'sofar' is not installed, so {path} cannot be read.\n"
            f"    Install it with:  pip install sofar\n"
            f"    Falling back to the analytic model.",
            file=sys.stderr,
        )
        return None

    sofa = sofar.read_sofa(path)
    ir = np.asarray(sofa.Data_IR)              # (measurements, receivers, samples)
    fs_measured = float(np.atleast_1d(sofa.Data_SamplingRate)[0])
    pos = np.asarray(sofa.SourcePosition)      # (measurements, 3)
    units = getattr(sofa, "SourcePosition_Type", "spherical")

    if str(units).lower().startswith("cart"):
        dirs = pos / np.linalg.norm(pos, axis=1, keepdims=True)
    else:
        az = np.radians(pos[:, 0])
        el = np.radians(pos[:, 1])
        dirs = np.stack(
            [np.cos(el) * np.cos(az), np.cos(el) * np.sin(az), np.sin(el)], axis=1
        )

    if verbose:
        print(f"  measured set: {ir.shape[0]} directions, "
              f"{ir.shape[2]} taps at {fs_measured:.0f} Hz")

    def provider(direction, n_taps, sample_rate):
        d = np.asarray(direction, float)
        d = d / np.linalg.norm(d)
        idx = int(np.argmax(dirs @ d))
        pair = ir[idx]  # (2, samples)

        if abs(sample_rate - fs_measured) > 1.0:
            # Linear resample. Good enough: HRIRs are smooth and short, and
            # any measured set beats an analytic one even slightly resampled.
            n_out = int(round(pair.shape[1] * sample_rate / fs_measured))
            src_t = np.arange(pair.shape[1]) / fs_measured
            dst_t = np.arange(n_out) / sample_rate
            pair = np.stack([np.interp(dst_t, src_t, pair[e]) for e in range(2)])

        out = np.zeros((2, n_taps))
        n = min(n_taps, pair.shape[1])
        out[:, :n] = pair[:, :n]
        return out

    return provider


def format_float_array(name: str, values: np.ndarray, per_line: int = 6) -> str:
    lines = [f"const float {name}[{values.size}] = {{"]
    flat = values.reshape(-1)
    for i in range(0, flat.size, per_line):
        chunk = ", ".join(f"{v:+.9e}f" for v in flat[i : i + per_line])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def write_header(
    path: Path,
    filters: np.ndarray,
    decims: dict,
    a2b: np.ndarray,
    args,
    source_label: str,
):
    n_ch, n_ear, n_taps = filters.shape
    assert (n_ch, n_ear) == (4, 2)

    peak = float(np.max(np.abs(filters)))
    energy = float(np.sum(filters**2))

    body = f"""// qpr_coeffs.h -- GENERATED FILE, DO NOT EDIT BY HAND
//
// Vendor: Illicit Apothecary
// Generated by sim/build_hrtf.py
//
// Regenerate with:
//     cd sim && python3 build_hrtf.py {" ".join(sys.argv[1:])}
//
// HRTF source          : {source_label}
// Monitor sample rate  : {args.rate:.0f} Hz
// Binaural FIR taps    : {n_taps}
// Capsule radius       : {args.radius * 1000:.1f} mm
// Virtual speakers     : 8 (cube vertices)
// Decoder              : projection, {"max-rE" if not args.basic else "basic"}
// Decimator taps       : {args.decim_taps} (tables for {", ".join(f"{k}:1" for k in sorted(decims))})
// Peak filter tap      : {peak:.6f}
// Total filter energy  : {energy:.6f}
//
// The four B-format channels are ordered [W, X, Y, Z] with SN3D
// normalisation, matching sim/qpr_ambisonics.py. See docs/CALIBRATION.md.

#pragma once
#include <stdint.h>

namespace qpr {{
namespace coeffs {{

constexpr uint32_t kHrtfTaps      = {n_taps};
constexpr uint32_t kDecimatorTaps = {args.decim_taps};
constexpr uint32_t kMonitorRateHz = {int(args.rate)};
constexpr float    kCapsuleRadiusMeters = {args.radius:.6f}f;

// Binaural filters, flattened as [channel][ear][tap]:
//   index = ((channel * 2) + ear) * kHrtfTaps + tap
// channel 0 = W, 1 = X, 2 = Y, 3 = Z;  ear 0 = left, 1 = right.
extern const float kBinauralFir[{filters.size}];

// Anti-alias low-passes applied before decimating the capture rate down to
// the monitor rate. Unity DC gain. One table per supported capture rate:
//   kDecimatorFir4 : 192 kHz -> 48 kHz  (the 4-channel dual-I2S mode)
//   kDecimatorFir2 :  96 kHz -> 48 kHz  (the single-line TDM fallback)
// Each is designed for ITS OWN input rate; using the wrong one lets
// ultrasonic content fold straight into the audible band.
extern const float kDecimatorFir4[{args.decim_taps}];
extern const float kDecimatorFir2[{args.decim_taps}];

// A-format to B-format matrix, flattened row-major as [bformat][capsule]:
//   index = bformat * 4 + capsule
// capsule order is FLU, FRD, BLD, BRU -- the order the capture driver
// delivers, which is fixed by the PCM1864 input wiring.
extern const float kAtoB[16];

}}  // namespace coeffs
}}  // namespace qpr
"""

    src = f"""// qpr_coeffs.cpp -- GENERATED FILE, DO NOT EDIT BY HAND
// Vendor: Illicit Apothecary  |  Generated by sim/build_hrtf.py

#include "qpr_coeffs.h"

namespace qpr {{
namespace coeffs {{

{format_float_array("kBinauralFir", filters)}

{format_float_array("kDecimatorFir4", decims[4])}

{format_float_array("kDecimatorFir2", decims[2])}

{format_float_array("kAtoB", a2b, per_line=4)}

}}  // namespace coeffs
}}  // namespace qpr
"""

    path.write_text(body)
    path.with_suffix(".cpp").write_text(src)
    print(f"  wrote {path}")
    print(f"  wrote {path.with_suffix('.cpp')}")


def write_binary(path: Path, filters: np.ndarray, args, source_label: str):
    """SD-card override file.

    Layout, all little-endian:
        0   'QPRH'                4 bytes
        4   version               uint32  (currently 1)
        8   sample rate           uint32
        12  taps                  uint32
        16  channels (always 4)   uint32
        20  ears (always 2)       uint32
        24  reserved              uint32 x 2
        32  float32 x (4*2*taps), ordered [channel][ear][tap]
    """
    n_ch, n_ear, n_taps = filters.shape
    with open(path, "wb") as f:
        f.write(MAGIC)
        f.write(struct.pack("<IIIIIII", FORMAT_VERSION, int(args.rate), n_taps,
                            n_ch, n_ear, 0, 0))
        f.write(filters.astype("<f4").tobytes())
    print(f"  wrote {path}  ({path.stat().st_size} bytes, {source_label})")
    print(f"  copy it to the root of the microSD card to override the built-in set")


def main() -> int:
    here = Path(__file__).resolve().parent
    default_out = here.parent / "lib" / "qpr_dsp" / "qpr_coeffs.h"

    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--taps", type=int, default=256,
                   help="binaural FIR length (default 256)")
    p.add_argument("--rate", type=float, default=48000.0,
                   help="monitor sample rate (default 48000)")
    p.add_argument("--decim-from", type=float, default=192000.0,
                   help="capture sample rate (default 192000)")
    p.add_argument("--decim-taps", type=int, default=qa.DECIMATOR_TAPS,
                   help=f"decimator FIR length (default {qa.DECIMATOR_TAPS})")
    p.add_argument("--radius", type=float, default=0.015,
                   help="capsule array radius in metres (default 0.015)")
    p.add_argument("--basic", action="store_true",
                   help="use a basic decoder instead of max-rE")
    p.add_argument("--no-correction", action="store_true",
                   help="skip the A-format correction filters")
    p.add_argument("--sofa", type=str, default=None,
                   help="path to a measured HRTF set in SOFA format")
    p.add_argument("--out", type=Path, default=default_out,
                   help="C header to write")
    p.add_argument("--bin", type=Path, default=None,
                   help="also write an SD-card override file here")
    p.add_argument("--no-header", action="store_true",
                   help="skip writing the C header (useful with --bin)")
    args = p.parse_args()

    print("qpr build_hrtf")
    print("  running the shared maths self-test first...")
    if not qa.self_test(verbose=False):
        print("  ! self-test FAILED -- refusing to generate coefficients")
        qa.self_test(verbose=True)
        return 1
    print("  self-test passed")

    provider = None
    source_label = "analytic spherical-head model (Brown & Duda + pinna + torso)"
    if args.sofa:
        provider = make_sofa_provider(args.sofa)
        if provider is not None:
            source_label = f"measured SOFA set: {Path(args.sofa).name}"

    decimation = int(round(args.decim_from / args.rate))
    if abs(args.decim_from / args.rate - decimation) > 1e-9:
        print(f"  ! capture rate {args.decim_from} is not an integer multiple of "
              f"monitor rate {args.rate}")
        return 1

    filters = qa.build_binaural_filters(
        n_taps=args.taps,
        sample_rate=args.rate,
        capsule_radius=args.radius,
        hrir_provider=provider,
        max_re=not args.basic,
        apply_a_format_correction=not args.no_correction,
    )
    # One anti-alias filter per supported capture rate. The 96 kHz TDM
    # fallback needs its own: a filter designed for a 192 kHz input has its
    # cutoff in completely the wrong place when fed 96 kHz samples.
    decims = {
        4: qa.design_decimation_fir(args.decim_taps, 4, args.rate * 4),
        2: qa.design_decimation_fir(args.decim_taps, 2, args.rate * 2),
    }
    a2b = qa.a_to_b_matrix()

    # Sanity: the W filter pair should carry most of the energy, and the pair
    # should be near-symmetric between ears (a symmetric virtual layout and a
    # symmetric head model).
    w_energy = float(np.sum(filters[0] ** 2))
    total = float(np.sum(filters**2))
    asym = float(np.max(np.abs(filters[0, 0] - filters[0, 1])))
    print(f"  W channel holds {100 * w_energy / total:.1f}% of the filter energy")
    print(f"  W left/right asymmetry: {asym:.2e} (should be tiny)")

    if not args.no_header:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        write_header(args.out, filters, decims, a2b, args, source_label)

    if args.bin:
        write_binary(args.bin, filters, args, source_label)

    print("  done")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
