M48
; DRILL file KiCad 10.0.4 date 2026-07-25T09:17:04
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-25T09:17:04-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X125.0Y-166.55
X136.43Y-166.55
T2
X127.13Y-160.2
T3
X7.0Y-7.0
X7.0Y-167.0
X48.96Y-23.0
X48.96Y-67.0
X125.04Y-23.0
X125.04Y-67.0
X167.0Y-7.0
X167.0Y-167.0
M30
