// qpr_coeffs.h -- GENERATED FILE, DO NOT EDIT BY HAND
//
// Vendor: Illicit Apothecary
// Generated by sim/build_hrtf.py
//
// Regenerate with:
//     cd sim && python3 build_hrtf.py --taps 128
//
// HRTF source          : analytic spherical-head model (Brown & Duda + pinna + torso)
// Monitor sample rate  : 48000 Hz
// Binaural FIR taps    : 128
// Capsule radius       : 15.0 mm
// Virtual speakers     : 8 (cube vertices)
// Decoder              : projection, max-rE
// Decimator taps       : 192 (tables for 2:1, 4:1)
// Peak filter tap      : 0.541015
// Total filter energy  : 1.021632
//
// The four B-format channels are ordered [W, X, Y, Z] with SN3D
// normalisation, matching sim/qpr_ambisonics.py. See docs/CALIBRATION.md.

#pragma once
#include <stdint.h>

namespace qpr {
namespace coeffs {

constexpr uint32_t kHrtfTaps      = 128;
constexpr uint32_t kDecimatorTaps = 192;
constexpr uint32_t kMonitorRateHz = 48000;
constexpr float    kCapsuleRadiusMeters = 0.015000f;

// Binaural filters, flattened as [channel][ear][tap]:
//   index = ((channel * 2) + ear) * kHrtfTaps + tap
// channel 0 = W, 1 = X, 2 = Y, 3 = Z;  ear 0 = left, 1 = right.
extern const float kBinauralFir[1024];

// Anti-alias low-passes applied before decimating the capture rate down to
// the monitor rate. Unity DC gain. One table per supported capture rate:
//   kDecimatorFir4 : 192 kHz -> 48 kHz  (the 4-channel dual-I2S mode)
//   kDecimatorFir2 :  96 kHz -> 48 kHz  (the single-line TDM fallback)
// Each is designed for ITS OWN input rate; using the wrong one lets
// ultrasonic content fold straight into the audible band.
extern const float kDecimatorFir4[192];
extern const float kDecimatorFir2[192];

// A-format to B-format matrix, flattened row-major as [bformat][capsule]:
//   index = bformat * 4 + capsule
// capsule order is FLU, FRD, BLD, BRU -- the order the capture driver
// delivers, which is fixed by the PCM1864 input wiring.
extern const float kAtoB[16];

}  // namespace coeffs
}  // namespace qpr
