M48
; DRILL file KiCad 10.0.4 date 2026-07-19T15:17:52
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-19T15:17:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X93.0Y-45.07
X93.0Y-56.5
T2
X86.65Y-54.37
T3
X4.0Y-4.0
X9.0Y-21.25
X9.0Y-63.25
X87.0Y-21.25
X87.0Y-63.25
X92.0Y-4.0
M30
